export const DEFAULT_URL='http://127.0.0.1:10000/v1/chat/completions';
export const CONFIG={text_url:DEFAULT_URL,api_key:'',model:'local'};
export class LLMError extends Error{}
export function configureText(url:string,apiKey?:string|null,model?:string|null){CONFIG.text_url=url.replace(/\/$/,'');if(apiKey!=null)CONFIG.api_key=apiKey.trim();if(model!=null)CONFIG.model=model.trim()||'local';}
export function completionsUrl(url:string){const u=url.replace(/\/$/,'');return u.endsWith('/chat/completions')?u:`${u}/chat/completions`;}
function headers(key=CONFIG.api_key){const h:Record<string,string>={'content-type':'application/json'};if(key)h.authorization=`Bearer ${key}`;return h;}
const sleep=(ms:number)=>new Promise(r=>setTimeout(r,ms));
async function fetchTimeout(url:string,init:RequestInit,timeout:number){const c=new AbortController(),t=setTimeout(()=>c.abort(),timeout);try{return await fetch(url,{...init,signal:c.signal})}finally{clearTimeout(t)}}
export async function chat(messages:any[],o:{url?:string,temperature?:number,max_tokens?:number,reasoning_effort?:string,timeout?:number}={}):Promise<string>{const url=completionsUrl(o.url||CONFIG.text_url);const payload={model:CONFIG.model||'local',messages,temperature:o.temperature??0,max_tokens:o.max_tokens??8192,reasoning_effort:o.reasoning_effort??'low'};let last:any;for(let attempt=1;attempt<=3;attempt++){try{const r=await fetchTimeout(url,{method:'POST',headers:headers(),body:JSON.stringify(payload)},o.timeout??300000);if(!r.ok){if([429,500,502,503,504].includes(r.status)&&attempt<3){await sleep(5000*attempt);continue;}throw new LLMError(`server ${r.status} at ${url} (model=${JSON.stringify(payload.model)})`);}const data:any=await r.json();const content=data?.choices?.[0]?.message?.content;if(typeof content!=='string')throw new LLMError(`unexpected server response shape: ${JSON.stringify(data).slice(0,800)}`);return content;}catch(e){last=e;if(e instanceof LLMError)throw e;if(attempt<3){await sleep(5000*attempt);continue;}}}throw new LLMError(`no answer from ${url} after 3 attempts: ${last}`);}
export function stripFences(text:string){let t=text.trim();if(t.startsWith('```')){t=t.includes('\n')?t.split('\n').slice(1).join('\n'):t;if(t.trimEnd().endsWith('```'))t=t.trimEnd().slice(0,-3);}return t.trim();}
export async function extractJson(messages:any[],o:{required_keys?:string[],attempts?:number}&Record<string,any>={}):Promise<Record<string,any>>{const{required_keys:rk,attempts:att,...chatOpts}=o;const convo=[...messages];let last='';for(let i=0;i<(att??3);i++){const raw=await chat(convo,chatOpts);try{const obj=JSON.parse(stripFences(raw));const miss=(rk??[]).filter(k=>!(k in obj));if(!miss.length)return obj;last=`missing required keys: ${miss.join(', ')}`;}catch(e){last=`invalid JSON: ${e}`;}convo.push({role:'assistant',content:raw},{role:'user',content:`Your reply failed validation (${last}). Reply with CORRECTED JSON only, same schema, no commentary.`});}throw new LLMError(`extraction failed after ${att??3} attempts: ${last}`);}
export async function getStatus(url:string,timeout=3000,apiKey?:string|null):Promise<number|null>{try{const r=await fetchTimeout(url,{headers:headers(apiKey??CONFIG.api_key)},timeout);return r.status;}catch{return null}}
export async function serverUp(url=CONFIG.text_url,timeout=3000){let base=url.replace(/\/$/,'');for(const tail of ['/v1/chat/completions','/v1'])if(base.endsWith(tail))base=base.slice(0,-tail.length);if(await getStatus(`${base}/health`,timeout)===200)return true;return await getStatus(`${base}/v1/models`,timeout)!==null;}
export async function verifyText(timeout=90000){const t=Date.now();const r=await fetchTimeout(completionsUrl(CONFIG.text_url),{method:'POST',headers:headers(),body:JSON.stringify({model:CONFIG.model||'local',messages:[{role:'user',content:'Answer with exactly: pong'}],temperature:0,max_tokens:256,reasoning_effort:'low'})},timeout);if(!r.ok)throw new LLMError(`HTTP ${r.status}`);const d:any=await r.json();const m=d?.choices?.[0]?.message??{};const reply=String(m.content||m.reasoning_content||'').trim();return{ok:true,latency_s:Math.round((Date.now()-t)/100)/10,reply:reply.slice(0,120)}}
